name: C++ CI/CD

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

      # 3️⃣ Debug build with sanitizers
      - name: Configure Debug Build with Sanitizers
        run: cmake -S . -B build_debug -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITIZERS=ON

      - name: Build Debug
        run: cmake --build build_debug

      - name: Run Unit Tests (Debug + Sanitizers)
        run: ASAN_OPTIONS=detect_leaks=1:abort_on_error=1:color=always ctest --test-dir build_debug --output-on-failure

      # 4️⃣ Release build (only if Debug/tests passed)
      - name: Configure Release Build
        run: cmake -S . -B build_release -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        run: cmake --build build_release

      # 5️⃣ Upload Release binary as artifact
      - name: Upload Release Binary
        uses: actions/upload-artifact@v3
        with:
          name: my_app_release
          path: build_release/main
